"use client";
import { useEffect, useState } from "react";
import type { UseFormRegister } from "react-hook-form";
import type { GeneratorInput } from "@/types";

type Props = { register: UseFormRegister<GeneratorInput>; values: Pick<GeneratorInput, "region" | "province" | "city" | "barangay">; setValue: (name: keyof GeneratorInput, value: string) => void };
async function load(path: string) { const r = await fetch(path); if (!r.ok) throw new Error(); return r.json() as Promise<string[]>; }

export function LocationPicker({ register, values, setValue }: Props) {
  const [regions, setRegions] = useState<string[]>([]), [provinces, setProvinces] = useState<string[]>([]), [cities, setCities] = useState<string[]>([]), [barangays, setBarangays] = useState<string[]>([]), [failed, setFailed] = useState(false);
  useEffect(() => { load("/api/locations?level=regions").then(setRegions).catch(() => setFailed(true)); }, []);
  useEffect(() => { if (!values.region) return setProvinces([]); load(`/api/locations?level=provinces&region=${encodeURIComponent(values.region)}`).then(setProvinces).catch(() => setFailed(true)); }, [values.region]);
  useEffect(() => { if (!values.region || !values.province) return setCities([]); load(`/api/locations?level=cities-municipalities&region=${encodeURIComponent(values.region)}&province=${encodeURIComponent(values.province)}`).then(setCities).catch(() => setFailed(true)); }, [values.region,values.province]);
  useEffect(() => { if (!values.region || !values.province || !values.city) return setBarangays([]); load(`/api/locations?level=barangays&region=${encodeURIComponent(values.region)}&province=${encodeURIComponent(values.province)}&city=${encodeURIComponent(values.city)}`).then(setBarangays).catch(() => setFailed(true)); }, [values.region,values.province,values.city]);
  const choose=(name:keyof GeneratorInput, value:string)=>{setValue(name,value); if(name==="region"){setValue("province","");setValue("city","");setValue("barangay","")} if(name==="province"){setValue("city","");setValue("barangay","")} if(name==="city")setValue("barangay","")};
  return <div><h2 className="text-2xl font-bold">🇵🇭 Philippine context <span className="text-sm font-normal text-slate-500">(optional)</span></h2><p className="mt-2 text-slate-600">Choose a location from nationwide PSGC data. Local facts always need verification.</p>{failed && <p className="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-800">Location lists are unavailable right now; you can type your location instead.</p>}<div className="mt-6 grid gap-4 sm:grid-cols-2"><Picker label="Region" name="region" items={regions} value={values.region||""} onChange={choose} register={register}/><Picker label="Province" name="province" items={provinces} value={values.province||""} onChange={choose} register={register}/><Picker label="City or Municipality" name="city" items={cities} value={values.city||""} onChange={choose} register={register}/><Picker label="Barangay" name="barangay" items={barangays} value={values.barangay||""} onChange={choose} register={register}/></div><label className="mt-5 block font-medium">School, hospital, or organization <span className="font-normal text-slate-500">(optional)</span><input className="field mt-1" placeholder="e.g., your school, a hospital, clinic, or barangay office" {...register("organization")}/></label></div>;
}
function Picker({ label,name,items,value,onChange,register }:{label:string;name:"region"|"province"|"city"|"barangay";items:string[];value:string;onChange:(name:keyof GeneratorInput,value:string)=>void;register:UseFormRegister<GeneratorInput>}){const field=register(name);return <label className="font-medium">{label}<input className="field mt-1" list={`${name}-options`} {...field} value={value} placeholder={items.length?`Search ${label.toLowerCase()}…`:`Select ${name==="region"?"a region first":"a parent location first"}`} onChange={e=>{field.onChange(e);onChange(name,e.target.value)}}/><datalist id={`${name}-options`}>{items.map(x=><option value={x} key={x}/>)}</datalist></label>}
